// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQXzAriNOnW4ho_SIcweeA659W9FsuQQ',
    appId: '1:333407764673:web:2829b64a7a3d6428d39440',
    messagingSenderId: '333407764673',
    projectId: 'quiz-app-dca03',
    authDomain: 'quiz-app-dca03.firebaseapp.com',
    storageBucket: 'quiz-app-dca03.firebasestorage.app',
    measurementId: 'G-2FPTQ4K88Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVspUuH4vCzB7PfnG3b4m4QTsyeDgv91s',
    appId: '1:333407764673:android:35bd37604ae2d07fd39440',
    messagingSenderId: '333407764673',
    projectId: 'quiz-app-dca03',
    storageBucket: 'quiz-app-dca03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4mikvaX7hy9TQSg1RWwWahpXMY_Nic2A',
    appId: '1:333407764673:ios:77119a1fb97f4fd7d39440',
    messagingSenderId: '333407764673',
    projectId: 'quiz-app-dca03',
    storageBucket: 'quiz-app-dca03.firebasestorage.app',
    iosBundleId: 'com.sunil93021.quizapp.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4mikvaX7hy9TQSg1RWwWahpXMY_Nic2A',
    appId: '1:333407764673:ios:77119a1fb97f4fd7d39440',
    messagingSenderId: '333407764673',
    projectId: 'quiz-app-dca03',
    storageBucket: 'quiz-app-dca03.firebasestorage.app',
    iosBundleId: 'com.sunil93021.quizapp.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbQXzAriNOnW4ho_SIcweeA659W9FsuQQ',
    appId: '1:333407764673:web:e8bee7df08e1c57cd39440',
    messagingSenderId: '333407764673',
    projectId: 'quiz-app-dca03',
    authDomain: 'quiz-app-dca03.firebaseapp.com',
    storageBucket: 'quiz-app-dca03.firebasestorage.app',
    measurementId: 'G-48CD8ZR0G5',
  );
}
